default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: saas_development

test:
  <<: *default
  database: saas_test

production:
  <<: *default
  host: ec2-54-217-202-108.eu-west-1.compute.amazonaws.com
  database: d4bpdpijckm715
  username: tzlmjcjlxbzqmk
  port: 5432
  password: 3Gqt77wR1xYRXvAoEb3Na3-KCd

