default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: saas_development

test:
  <<: *default
  database: saas_test

production:
  <<: *default
  host: ec2-79-125-117-94.eu-west-1.compute.amazonaws.com
  database: dd07fop0sj8bvl
  username: zcqfnjdxtppiyh
  port: 5432
  password: Lt4rQzbrWzR1Xd4bv33hdGEvX4

